; Source code in this file from Noshell v1.2
; (C) 2007 by Brandon Wilson. All rights reserved.

TI83P EQU 1
TI73 EQU 2
CALC EQU TI83P
BETA EQU 1 
PROD EQU 2
DEV EQU PROD

 DEFINE TIOSCHECK
 DEFINE Main, Space=ROM
 DEFINE TextSpace, Space=ROM
 DEFINE Header, Space=ROM
 DEFINE MemVars, Space=ROM
MajorTIOSVersion EQU 2
MinorTIOSVersion EQU 30
Version EQU 1
AppName EQU "CalcUtil"

